# Change these first
owner: androidkitkat # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Matrix
    url: https://matrix.eisemann.us
  - name: Yld.Moe
    url: https://yld.moe
  - name: Personal Site
    url: https://michaeleisemann.com
  - name: Gitea
    url: https://code.michaeleisemann.com
  - name: ZNC
    url: https://znc.waifupaste.moe:42069
  - name: Music
    url: https://music.graped.net
  - name: HOA
    url: https://severnpineshoa.com
  - name: HOA Cloud
    url: https://cloud.severnpineshoa.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.michaeleisemann.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: mae
  introTitle:  
  introMessage: 
  robotsText: "User-agent: *\n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - androidkitkat

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
